                                                            
magick convert "Ad Hoc.ico" "Ad Hoc.ico.png"                                                    
magick convert "Add Data.ico" "Add Data.ico.png"                                                
magick convert "Add Stock Aliquot.ico" "Add Stock Aliquot.ico.png"                              
magick convert "AddLibrary.ico" "AddLibrary.ico.png"                                            
magick convert "Address.ico" "Address.ico.png"                                                  
magick convert "AddSubSystem.ico" "AddSubSystem.ico.png"                                        
magick convert "AddSuite.ico" "AddSuite.ico.png"                                                
magick convert "AddTest.ico" "AddTest.ico.png"                                                  
magick convert "AddXMLFile.ico" "AddXMLFile.ico.png"                                            
magick convert "Add_Over.ico" "Add_Over.ico.png"                                                
magick convert "Alert.ico" "Alert.ico.png"                                                      
magick convert "Aliquot Buffer List.ico" "Aliquot Buffer List.ico.png"                          
magick convert "Aliquot Buffer.ico" "Aliquot Buffer.ico.png"                                    
magick convert "aliquot composite.ico" "aliquot composite.ico.png"                              
magick convert "aliquot hierarchy.ico" "aliquot hierarchy.ico.png"                              
magick convert "Aliquot Login.ico" "Aliquot Login.ico.png"                                      
magick convert "aliquot split.ico" "aliquot split.ico.png"                                      
magick convert "Aliquot.ico" "Aliquot.ico.png"                                                  
magick convert "AliquotA.ico" "AliquotA.ico.png"                                                
magick convert "AliquotC.ico" "AliquotC.ico.png"                                                
magick convert "AliquotI.ico" "AliquotI.ico.png"                                                
magick convert "AliquotP.ico" "AliquotP.ico.png"                                                
magick convert "AliquotR.ico" "AliquotR.ico.png"                                                
magick convert "AliquotResult.ico" "AliquotResult.ico.png"                                      
magick convert "AliquotS.ico" "AliquotS.ico.png"                                                
magick convert "AliquotU.ico" "AliquotU.ico.png"                                                
magick convert "AliquotUq.ico" "AliquotUq.ico.png"                                              
magick convert "AliquotV.ico" "AliquotV.ico.png"                                                
magick convert "AliquotW.ico" "AliquotW.ico.png"                                                
magick convert "AliquotX.ico" "AliquotX.ico.png"                                                
magick convert "aliquot_analyte.ico" "aliquot_analyte.ico.png"                                  
magick convert "Aliquot_Definition.ico" "Aliquot_Definition.ico.png"                            
magick convert "amount.ico" "amount.ico.png"                                                    
magick convert "Analysis.ico" "Analysis.ico.png"                                                
magick convert "Analyte.ico" "Analyte.ico.png"                                                  
magick convert "Andy.ico" "Andy.ico.png"                                                        
magick convert "anicon.ico" "anicon.ico.png"                                                    
magick convert "Application.ico" "Application.ico.png"                                          
magick convert "ApplicationTemplate.ico" "ApplicationTemplate.ico.png"                          
magick convert "aqc block.ico" "aqc block.ico.png"                                              
magick convert "aqc chart.ico" "aqc chart.ico.png"                                              
magick convert "aqc failure.ico" "aqc failure.ico.png"                                          
magick convert "aqc point.ico" "aqc point.ico.png"                                              
magick convert "aqc rule.ico" "aqc rule.ico.png"                                                
magick convert "ArchivedAliquot.ico" "ArchivedAliquot.ico.png"                                  
magick convert "ArchivedGeneric.ico" "ArchivedGeneric.ico.png"                                  
magick convert "ArchivedPlate Plan.ico" "ArchivedPlate Plan.ico.png"                            
magick convert "ArchivedPlate.ico" "ArchivedPlate.ico.png"                                      
magick convert "ArchivedPlatePlanStep.ico" "ArchivedPlatePlanStep.ico.png"                      
magick convert "ArchivedRack.ico" "ArchivedRack.ico.png"                                        
magick convert "ArchivedResult.ico" "ArchivedResult.ico.png"                                    
magick convert "ArchivedSample.ico" "ArchivedSample.ico.png"                                    
magick convert "Archivedsdg.ico" "Archivedsdg.ico.png"                                          
magick convert "ArchivedStock.ico" "ArchivedStock.ico.png"                                      
magick convert "ArchivedStudy.ico" "ArchivedStudy.ico.png"                                      
magick convert "ArchivedTest.ico" "ArchivedTest.ico.png"                                        
magick convert "ArchivedWorksheet.ico" "ArchivedWorksheet.ico.png"                              
magick convert "Archived_Hierarchy.ico" "Archived_Hierarchy.ico.png"                            
magick convert "Archived_Set.ico" "Archived_Set.ico.png"                                        
magick convert "Archived_Set_Wizard.ico" "Archived_Set_Wizard.ico.png"                          
magick convert "Archiving Dialog.ico" "Archiving Dialog.ico.png"                                
magick convert "argument.ico" "argument.ico.png"                                                
magick convert "argument_aliquot.ico" "argument_aliquot.ico.png"                                
magick convert "argument_av.ico" "argument_av.ico.png"                                          
magick convert "argument_chemical.ico" "argument_chemical.ico.png"                              
magick convert "argument_client_fact.ICO" "argument_client_fact.ICO.png"                        
magick convert "argument_cont_fact.ico" "argument_cont_fact.ico.png"                            
magick convert "argument_inst_fact.ico" "argument_inst_fact.ico.png"                            
magick convert "argument_prod_fact.ico" "argument_prod_fact.ico.png"                            
magick convert "Argument_rlp.ico" "Argument_rlp.ico.png"                                        
magick convert "Argument_rsa.ico" "Argument_rsa.ico.png"                                        
magick convert "Argument_rsp.ico" "Argument_rsp.ico.png"                                        
magick convert "Argument_rst.ico" "Argument_rst.ico.png"                                        
magick convert "arrow_cw.ico" "arrow_cw.ico.png"                                                
magick convert "Audit.ico" "Audit.ico.png"                                                      
magick convert "Authorise.ico" "Authorise.ico.png"                                              
magick convert "authorised stamp.ico" "authorised stamp.ico.png"                                
magick convert "Axis.ico" "Axis.ico.png"                                                        
magick convert "BackgroundSetup.ico" "BackgroundSetup.ico.png"                                  
magick convert "BGP.ico" "BGP.ico.png"                                                          
magick convert "Bio-hazard.ico" "Bio-hazard.ico.png"                                            
magick convert "BMP_file.ico" "BMP_file.ico.png"                                                
magick convert "bottler.ico" "bottler.ico.png"                                                  
magick convert "calculation.ico" "calculation.ico.png"                                          
magick convert "Calendar.ico" "Calendar.ico.png"                                                
magick convert "camera.ico" "camera.ico.png"                                                    
magick convert "cancelled stamp.ico" "cancelled stamp.ico.png"                                  
magick convert "cancel_overlay.ico" "cancel_overlay.ico.png"                                    
magick convert "card.ico" "card.ico.png"                                                        
magick convert "cell_template.ico" "cell_template.ico.png"                                      
magick convert "Change Role.ico" "Change Role.ico.png"                                          
magick convert "chemical.ico" "chemical.ico.png"                                                
magick convert "chemical_calculator.ico" "chemical_calculator.ico.png"                          
magick convert "CherryPickingAliquot.ico" "CherryPickingAliquot.ico.png"                        
magick convert "CHOtFc.ico" "CHOtFc.ico.png"                                                    
magick convert "Clear Well.ico" "Clear Well.ico.png"                                            
magick convert "ClearFilterGrid.ico" "ClearFilterGrid.ico.png"                                  
magick convert "Client.ico" "Client.ico.png"                                                    
magick convert "closed.ico" "closed.ico.png"                                                    
magick convert "cofa template.ico" "cofa template.ico.png"                                      
magick convert "cofa.ico" "cofa.ico.png"                                                        
magick convert "Coke.ico" "Coke.ico.png"                                                        
magick convert "Colin.ico" "Colin.ico.png"                                                      
magick convert "Colour.ico" "Colour.ico.png"                                                    
magick convert "command.ico" "command.ico.png"                                                  
magick convert "Comment.ico" "Comment.ico.png"                                                  
magick convert "complete.ico" "complete.ico.png"                                                
magick convert "Composite.ico" "Composite.ico.png"                                              
magick convert "conclusion.ico" "conclusion.ico.png"                                            
magick convert "conected.ico" "conected.ico.png"                                                
magick convert "config.ico" "config.ico.png"                                                    
magick convert "constant.ico" "constant.ico.png"                                                
magick convert "Contact.ico" "Contact.ico.png"                                                  
magick convert "container.ico" "container.ico.png"                                              
magick convert "Copy Down.ico" "Copy Down.ico.png"                                              
magick convert "Copy Left.ico" "Copy Left.ico.png"                                              
magick convert "Copy Right.ico" "Copy Right.ico.png"                                            
magick convert "Copy Up.ico" "Copy Up.ico.png"                                                  
magick convert "copy.ico" "copy.ico.png"                                                        
magick convert "copy2.ico" "copy2.ico.png"                                                      
magick convert "corrosive.ico" "corrosive.ico.png"                                              
magick convert "cross.ico" "cross.ico.png"                                                      
magick convert "CSV_file.ico" "CSV_file.ico.png"                                                
magick convert "data type boolean selected.ico" "data type boolean selected.ico.png"            
magick convert "Data Type Boolean.ico" "Data Type Boolean.ico.png"                              
magick convert "data type date selected.ico" "data type date selected.ico.png"                  
magick convert "Data Type Date.ico" "Data Type Date.ico.png"                                    
magick convert "data type link selected.ico" "data type link selected.ico.png"                  
magick convert "Data Type Link.ico" "Data Type Link.ico.png"                                    
magick convert "data type number selected.ico" "data type number selected.ico.png"              
magick convert "Data Type Number.ico" "Data Type Number.ico.png"                                
magick convert "data type phrase selected.ico" "data type phrase selected.ico.png"              
magick convert "Data Type Phrase.ico" "Data Type Phrase.ico.png"                                
magick convert "data type text selected.ico" "data type text selected.ico.png"                  
magick convert "Data Type Text.ico" "Data Type Text.ico.png"                                    
magick convert "data type unknown selected.ico" "data type unknown selected.ico.png"            
magick convert "Data Type Unknown.ico" "Data Type Unknown.ico.png"                              
magick convert "DataDestination.ico" "DataDestination.ico.png"                                  
magick convert "DataItem.ico" "DataItem.ico.png"                                                
magick convert "DataPackage.ico" "DataPackage.ico.png"                                          
magick convert "DataPackageX.ico" "DataPackageX.ico.png"                                        
magick convert "DateTime.ico" "DateTime.ico.png"                                                
magick convert "Debug.ico" "Debug.ico.png"                                                      
magick convert "definition_aliquot.ico" "definition_aliquot.ico.png"                            
magick convert "definition_result.ico" "definition_result.ico.png"                              
magick convert "definition_sample.ico" "definition_sample.ico.png"                              
magick convert "definition_sdg.ico" "definition_sdg.ico.png"                                    
magick convert "definition_test.ico" "definition_test.ico.png"                                  
magick convert "Delete Table.ico" "Delete Table.ico.png"                                        
magick convert "Delete.ico" "Delete.ico.png"                                                    
magick convert "Destination csv.ico" "Destination csv.ico.png"                                  
magick convert "Destination excel.ico" "Destination excel.ico.png"                              
magick convert "Destination Extension.ico" "Destination Extension.ico.png"                      
magick convert "Destination PSR.ico" "Destination PSR.ico.png"                                  
magick convert "Destination.ico" "Destination.ico.png"                                          
magick convert "Destination_EMail.ico" "Destination_EMail.ico.png"                              
magick convert "Destination_Enhanced_EMail.ico" "Destination_Enhanced_EMail.ico.png"            
magick convert "Destination_Export.ico" "Destination_Export.ico.png"                            
magick convert "Destination_Fax.ico" "Destination_Fax.ico.png"                                  
magick convert "Destination_Group.ico" "Destination_Group.ico.png"                              
magick convert "Destination_Local.ico" "Destination_Local.ico.png"                              
magick convert "Destination_Printer.ico" "Destination_Printer.ico.png"                          
magick convert "Destination_Stored.ico" "Destination_Stored.ico.png"                            
magick convert "Destination_User.ico" "Destination_User.ico.png"                                
magick convert "Details.ico" "Details.ico.png"                                                  
magick convert "DM.ico" "DM.ico.png"                                                            
magick convert "Down.ico" "Down.ico.png"                                                        
magick convert "EMail_Notification.ico" "EMail_Notification.ico.png"                            
magick convert "Empty.ico" "Empty.ico.png"                                                      
magick convert "Entity.ico" "Entity.ico.png"                                                    
magick convert "event link reset.ico" "event link reset.ico.png"                                
magick convert "event link set.ico" "event link set.ico.png"                                    
magick convert "ExcelXLSX_file.ico" "ExcelXLSX_file.ico.png"                                    
magick convert "Excel_file.ico" "Excel_file.ico.png"                                            
magick convert "Execute.ico" "Execute.ico.png"                                                  
magick convert "ExpandAll.ico" "ExpandAll.ico.png"                                              
magick convert "ExpandAllCancel.ico" "ExpandAllCancel.ico.png"                                  
magick convert "Explorer Columns.ico" "Explorer Columns.ico.png"                                
magick convert "Explorer.ico" "Explorer.ico.png"                                                
magick convert "ExplorerEnhanced.ico" "ExplorerEnhanced.ico.png"                                
magick convert "Explosive.ico" "Explosive.ico.png"                                              
magick convert "Export.ico" "Export.ico.png"                                                    
magick convert "Extension.ico" "Extension.ico.png"                                              
magick convert "extensionchoice.ico" "extensionchoice.ico.png"                                  
magick convert "factor.ico" "factor.ico.png"                                                    
magick convert "Fail.ico" "Fail.ico.png"                                                        
magick convert "Field Wizard.ico" "Field Wizard.ico.png"                                        
magick convert "Field.ico" "Field.ico.png"                                                      
magick convert "Field_Argument.ico" "Field_Argument.ico.png"                                    
magick convert "Field_Argument_Field.ico" "Field_Argument_Field.ico.png"                        
magick convert "FileExit.ico" "FileExit.ico.png"                                                
magick convert "Filter Argument.ico" "Filter Argument.ico.png"                                  
magick convert "Filter.ico" "Filter.ico.png"                                                    
magick convert "Find.ico" "Find.ico.png"                                                        
magick convert "First.ico" "First.ico.png"                                                      
magick convert "fit.ico" "fit.ico.png"                                                          
magick convert "flammable.ico" "flammable.ico.png"                                              
magick convert "FOLDER.ICO" "FOLDER.ICO.png"                                                    
magick convert "Folderc.ico" "Folderc.ico.png"                                                  
magick convert "Foldero.ico" "Foldero.ico.png"                                                  
magick convert "Format.ico" "Format.ico.png"                                                    
magick convert "FullRow.ico" "FullRow.ico.png"                                                  
magick convert "full_plate_template.ico" "full_plate_template.ico.png"                          
magick convert "Gas.ico" "Gas.ico.png"                                                          
magick convert "Generic.ico" "Generic.ico.png"                                                  
magick convert "Grade.ico" "Grade.ico.png"                                                      
magick convert "Graham.ico" "Graham.ico.png"                                                    
magick convert "Greg.ico" "Greg.ico.png"                                                        
magick convert "grid.ico" "grid.ico.png"                                                        
magick convert "Group.ico" "Group.ico.png"                                                      
magick convert "Hazard.ico" "Hazard.ico.png"                                                    
magick convert "hazardf.ico" "hazardf.ico.png"                                                  
magick convert "hazard_removed.ico" "hazard_removed.ico.png"                                    
magick convert "Help.ico" "Help.ico.png"                                                        
magick convert "Helpfile.ico" "Helpfile.ico.png"                                                
magick convert "Hierarchy.ico" "Hierarchy.ico.png"                                              
magick convert "HTML_file.ico" "HTML_file.ico.png"                                              
magick convert "Import.ico" "Import.ico.png"                                                    
magick convert "import_box.ico" "import_box.ico.png"                                            
magick convert "In Service.ico" "In Service.ico.png"                                            
magick convert "Increment.ico" "Increment.ico.png"                                              
magick convert "information.ico" "information.ico.png"                                          
magick convert "insert row.ico" "insert row.ico.png"                                            
magick convert "Insert Table.ico" "Insert Table.ico.png"                                        
magick convert "Insert.ico" "Insert.ico.png"                                                    
magick convert "InsertChildNode.ico" "InsertChildNode.ico.png"                                  
magick convert "InsertCommand.ico" "InsertCommand.ico.png"                                      
magick convert "InsertLower.ico" "InsertLower.ico.png"                                          
magick convert "InsertNode.ico" "InsertNode.ico.png"                                            
magick convert "InsertSeparator.ico" "InsertSeparator.ico.png"                                  
magick convert "InsertUpper.ico" "InsertUpper.ico.png"                                          
magick convert "Inspection Stamp.ico" "Inspection Stamp.ico.png"                                
magick convert "Inspection.ico" "Inspection.ico.png"                                            
magick convert "Instrument.ico" "Instrument.ico.png"                                            
magick convert "instruments_active.ico" "instruments_active.ico.png"                            
magick convert "instruments_active_o.ico" "instruments_active_o.ico.png"                        
magick convert "instruments_inactive.ico" "instruments_inactive.ico.png"                        
magick convert "instruments_inactive_o.ico" "instruments_inactive_o.ico.png"                    
magick convert "instrument_file.ico" "instrument_file.ico.png"                                  
magick convert "instrument_folder.ico" "instrument_folder.ico.png"                              
magick convert "instrument_group.ico" "instrument_group.ico.png"                                
magick convert "instrument_group_folder.ico" "instrument_group_folder.ico.png"                  
magick convert "instrument_new.ico" "instrument_new.ico.png"                                    
magick convert "Internat.ico" "Internat.ico.png"                                                
magick convert "Internationalisation.ico" "Internationalisation.ico.png"                        
magick convert "Irritant Noxious.ico" "Irritant Noxious.ico.png"                                
magick convert "Irritant.ico" "Irritant.ico.png"                                                
magick convert "item_security.ico" "item_security.ico.png"                                      
magick convert "Joe.ico" "Joe.ico.png"                                                          
magick convert "Jon.ico" "Jon.ico.png"                                                          
magick convert "Kevin.ico" "Kevin.ico.png"                                                      
magick convert "KEYBOARD.ICO" "KEYBOARD.ICO.png"                                                
magick convert "Last.ico" "Last.ico.png"                                                        
magick convert "Led Off.ico" "Led Off.ico.png"                                                  
magick convert "Led On.ico" "Led On.ico.png"                                                    
magick convert "Level Down.ico" "Level Down.ico.png"                                            
magick convert "Level Up.ico" "Level Up.ico.png"                                                
magick convert "Library.ico" "Library.ico.png"                                                  
magick convert "LibraryNotFinished.ico" "LibraryNotFinished.ico.png"                            
magick convert "LibraryNotPassed.ico" "LibraryNotPassed.ico.png"                                
magick convert "LibraryPassed.ico" "LibraryPassed.ico.png"                                      
magick convert "LibrarySel.ico" "LibrarySel.ico.png"                                            
magick convert "License.ico" "License.ico.png"                                                  
magick convert "ListView.ico" "ListView.ico.png"                                                
magick convert "ListViewFilter.ico" "ListViewFilter.ico.png"                                    
magick convert "LoadLibrary.ico" "LoadLibrary.ico.png"                                          
magick convert "LoadXMLFile.ico" "LoadXMLFile.ico.png"                                          
magick convert "Location.ico" "Location.ico.png"                                                
magick convert "location_new.ico" "location_new.ico.png"                                        
magick convert "lock session.ico" "lock session.ico.png"                                        
magick convert "login stock.ico" "login stock.ico.png"                                          
magick convert "Login.ico" "Login.ico.png"                                                      
magick convert "Logout.ico" "Logout.ico.png"                                                    
magick convert "Mail.ico" "Mail.ico.png"                                                        
magick convert "Mail2.ico" "Mail2.ico.png"                                                      
magick convert "Mail_2.ico" "Mail_2.ico.png"                                                    
magick convert "mail_letter.ICO" "mail_letter.ICO.png"                                          
magick convert "Map.ico" "Map.ico.png"                                                          
magick convert "Menu.ico" "Menu.ico.png"                                                        
magick convert "MHT_file.ico" "MHT_file.ico.png"                                                
magick convert "MicroHelp.ico" "MicroHelp.ico.png"                                              
magick convert "MicroHelpDisabled.ico" "MicroHelpDisabled.ico.png"                              
magick convert "miner.ico" "miner.ico.png"                                                      
magick convert "Monitor.ico" "Monitor.ico.png"                                                  
magick convert "Morgan.ico" "Morgan.ico.png"                                                    
magick convert "mouse1.ico" "mouse1.ico.png"                                                    
magick convert "mouse2.ico" "mouse2.ico.png"                                                    
magick convert "mouse3.ico" "mouse3.ico.png"                                                    
magick convert "mouse4.ico" "mouse4.ico.png"                                                    
magick convert "Move Down.ico" "Move Down.ico.png"                                              
magick convert "move Left.ico" "move Left.ico.png"                                              
magick convert "Move Reverse.ico" "Move Reverse.ico.png"                                        
magick convert "move Right.ico" "move Right.ico.png"                                            
magick convert "Move Up.ico" "Move Up.ico.png"                                                  
magick convert "Multiple Levels.ico" "Multiple Levels.ico.png"                                  
magick convert "Multiple.ico" "Multiple.ico.png"                                                
magick convert "MultiplePoints.ico" "MultiplePoints.ico.png"                                    
magick convert "Nautilus.ico" "Nautilus.ico.png"                                                
magick convert "NautilusXML.ico" "NautilusXML.ico.png"                                          
magick convert "Next Mandatory.ico" "Next Mandatory.ico.png"                                    
magick convert "None.ico" "None.ico.png"                                                        
magick convert "nosynchro.ico" "nosynchro.ico.png"                                              
magick convert "Note.ico" "Note.ico.png"                                                        
magick convert "ObjectLibrary.ico" "ObjectLibrary.ico.png"                                      
magick convert "Old Folderc.ico" "Old Folderc.ico.png"                                          
magick convert "Open.ico" "Open.ico.png"                                                        
magick convert "Operator.ico" "Operator.ico.png"                                                
magick convert "OrderA.ico" "OrderA.ico.png"                                                    
magick convert "OrderB.ico" "OrderB.ico.png"                                                    
magick convert "OrderC.ico" "OrderC.ico.png"                                                    
magick convert "OrderD.ico" "OrderD.ico.png"                                                    
magick convert "order_plate_template.ico" "order_plate_template.ico.png"                        
magick convert "outcalib.ico" "outcalib.ico.png"                                                
magick convert "Oxidising.ico" "Oxidising.ico.png"                                              
magick convert "PackageProperty.ico" "PackageProperty.ico.png"                                  
magick convert "PackagingRule.ico" "PackagingRule.ico.png"                                      
magick convert "PackagingSchedule.ico" "PackagingSchedule.ico.png"                              
magick convert "PackagingSyntax.ico" "PackagingSyntax.ico.png"                                  
magick convert "page.ico" "page.ico.png"                                                        
magick convert "parser.ico" "parser.ico.png"                                                    
magick convert "parts.ico" "parts.ico.png"                                                      
magick convert "part_new.ico" "part_new.ico.png"                                                
magick convert "Pass.ico" "Pass.ico.png"                                                        
magick convert "Password.ico" "Password.ico.png"                                                
magick convert "Paste As Child Aliquot.ico" "Paste As Child Aliquot.ico.png"                    
magick convert "paste2.ico" "paste2.ico.png"                                                    
magick convert "pause.ico" "pause.ico.png"                                                      
magick convert "PB Application.ico" "PB Application.ico.png"                                    
magick convert "PB DataPipeLine.ico" "PB DataPipeLine.ico.png"                                  
magick convert "PB DataWindow.ico" "PB DataWindow.ico.png"                                      
magick convert "PB Function.ico" "PB Function.ico.png"                                          
magick convert "PB Layer.ico" "PB Layer.ico.png"                                                
magick convert "PB Menu.ico" "PB Menu.ico.png"                                                  
magick convert "PB Project.ico" "PB Project.ico.png"                                            
magick convert "PB Query.ico" "PB Query.ico.png"                                                
magick convert "PB Structure.ico" "PB Structure.ico.png"                                        
magick convert "PB UserObject.ico" "PB UserObject.ico.png"                                      
magick convert "PB Window.ico" "PB Window.ico.png"                                              
magick convert "Pclip.ico" "Pclip.ico.png"                                                      
magick convert "PDF_file.ico" "PDF_file.ico.png"                                                
magick convert "Pedigree.ico" "Pedigree.ico.png"                                                
magick convert "PESBSTReport.ico" "PESBSTReport.ico.png"                                        
magick convert "Phil.ico" "Phil.ico.png"                                                        
magick convert "Phrase Note.ico" "Phrase Note.ico.png"                                          
magick convert "Phrase.ico" "Phrase.ico.png"                                                    
magick convert "Plate CherryP.ico" "Plate CherryP.ico.png"                                      
magick convert "Plate Compress.ico" "Plate Compress.ico.png"                                    
magick convert "Plate Editor.ico" "Plate Editor.ico.png"                                        
magick convert "Plate Fill Aliquot.ico" "Plate Fill Aliquot.ico.png"                            
magick convert "Plate Fill Mode.ico" "Plate Fill Mode.ico.png"                                  
magick convert "Plate Fill New Aliquot.ico" "Plate Fill New Aliquot.ico.png"                    
magick convert "Plate login.ico" "Plate login.ico.png"                                          
magick convert "Plate Merge.ico" "Plate Merge.ico.png"                                          
magick convert "Plate Move Source.ico" "Plate Move Source.ico.png"                              
magick convert "Plate Move Target.ico" "Plate Move Target.ico.png"                              
magick convert "Plate Plan Login.ico" "Plate Plan Login.ico.png"                                
magick convert "Plate Plan Template.ico" "Plate Plan Template.ico.png"                          
magick convert "Plate Plan.ico" "Plate Plan.ico.png"                                            
magick convert "Plate PlanA.ico" "Plate PlanA.ico.png"                                          
magick convert "Plate PlanC.ico" "Plate PlanC.ico.png"                                          
magick convert "Plate PlanDA.ico" "Plate PlanDA.ico.png"                                        
magick convert "Plate PlanI.ico" "Plate PlanI.ico.png"                                          
magick convert "Plate PlanP.ico" "Plate PlanP.ico.png"                                          
magick convert "Plate PlanR.ico" "Plate PlanR.ico.png"                                          
magick convert "Plate PlanS.ico" "Plate PlanS.ico.png"                                          
magick convert "Plate PlanU.ico" "Plate PlanU.ico.png"                                          
magick convert "Plate PlanV.ico" "Plate PlanV.ico.png"                                          
magick convert "Plate PlanX.ico" "Plate PlanX.ico.png"                                          
magick convert "Plate Probe.ico" "Plate Probe.ico.png"                                          
magick convert "Plate Remove Aliquot.ico" "Plate Remove Aliquot.ico.png"                        
magick convert "Plate Replicate.ico" "Plate Replicate.ico.png"                                  
magick convert "Plate Split.ico" "Plate Split.ico.png"                                          
magick convert "Plate Template Order.ico" "Plate Template Order.ico.png"                        
magick convert "Plate Template Sequence.ico" "Plate Template Sequence.ico.png"                  
magick convert "Plate Verify Inst.ico" "Plate Verify Inst.ico.png"                              
magick convert "Plate Verify.ico" "Plate Verify.ico.png"                                        
magick convert "Plate Zone.ico" "Plate Zone.ico.png"                                            
magick convert "Plate.ico" "Plate.ico.png"                                                      
magick convert "PlateA.ico" "PlateA.ico.png"                                                    
magick convert "PlateC.ico" "PlateC.ico.png"                                                    
magick convert "PlateI.ICO" "PlateI.ICO.png"                                                    
magick convert "PlateP.ICO" "PlateP.ICO.png"                                                    
magick convert "PlateR.ico" "PlateR.ico.png"                                                    
magick convert "PlateS.ico" "PlateS.ico.png"                                                    
magick convert "PlateU.ico" "PlateU.ico.png"                                                    
magick convert "PlateUq.ico" "PlateUq.ico.png"                                                  
magick convert "PlateV.ico" "PlateV.ico.png"                                                    
magick convert "PlateX.ico" "PlateX.ico.png"                                                    
magick convert "Plate_Dimensions.ico" "Plate_Dimensions.ico.png"                                
magick convert "Plate_new.ico" "Plate_new.ico.png"                                              
magick convert "plate_plan_step.ico" "plate_plan_step.ico.png"                                  
magick convert "Pollutant.ico" "Pollutant.ico.png"                                              
magick convert "Printer.ico" "Printer.ico.png"                                                  
magick convert "Product.ico" "Product.ico.png"                                                  
magick convert "Profile.ico" "Profile.ico.png"                                                  
magick convert "profile2.ico" "profile2.ico.png"                                                
magick convert "profile3.ico" "profile3.ico.png"                                                
magick convert "Project.ico" "Project.ico.png"                                                  
magick convert "Prompt.ico" "Prompt.ico.png"                                                    
magick convert "Prompt1.ico" "Prompt1.ico.png"                                                  
magick convert "Prompt2.ico" "Prompt2.ico.png"                                                  
magick convert "Prompt3.ico" "Prompt3.ico.png"                                                  
magick convert "Prompt4.ico" "Prompt4.ico.png"                                                  
magick convert "Prompt5.ico" "Prompt5.ico.png"                                                  
magick convert "propertyscript.ico" "propertyscript.ico.png"                                    
magick convert "rack empty.ico" "rack empty.ico.png"                                            
magick convert "rack full.ico" "rack full.ico.png"                                              
magick convert "Rack.ico" "Rack.ico.png"                                                        
magick convert "Rack_Fill.ico" "Rack_Fill.ico.png"                                              
magick convert "rack_new.ico" "rack_new.ico.png"                                                
magick convert "rack_remove.ico" "rack_remove.ico.png"                                          
magick convert "rack_split.ico" "rack_split.ico.png"                                            
magick convert "Rack_Type.ico" "Rack_Type.ico.png"                                              
magick convert "Rack_Verify.ico" "Rack_Verify.ico.png"                                          
magick convert "Radioactive.ico" "Radioactive.ico.png"                                          
magick convert "Reactive.ico" "Reactive.ico.png"                                                
magick convert "Read Write.ico" "Read Write.ico.png"                                            
magick convert "Read.ico" "Read.ico.png"                                                        
magick convert "Refresh.ico" "Refresh.ico.png"                                                  
magick convert "Reject.ico" "Reject.ico.png"                                                    
magick convert "Rejected Stamp.ico" "Rejected Stamp.ico.png"                                    
magick convert "Remove Data.ico" "Remove Data.ico.png"                                          
magick convert "Rename.ico" "Rename.ico.png"                                                    
magick convert "Reorder.ico" "Reorder.ico.png"                                                  
magick convert "Report Argument.ico" "Report Argument.ico.png"                                  
magick convert "Report.ico" "Report.ico.png"                                                    
magick convert "Reporting.ico" "Reporting.ico.png"                                              
magick convert "reset.ico" "reset.ico.png"                                                      
magick convert "Restore.ico" "Restore.ico.png"                                                  
magick convert "Result Authorisation.ico" "Result Authorisation.ico.png"                        
magick convert "Result.ico" "Result.ico.png"                                                    
magick convert "resulta.ico" "resulta.ico.png"                                                  
magick convert "resultc.ico" "resultc.ico.png"                                                  
magick convert "resulti.ico" "resulti.ico.png"                                                  
magick convert "resultp.ico" "resultp.ico.png"                                                  
magick convert "resultr.ico" "resultr.ico.png"                                                  
magick convert "results.ico" "results.ico.png"                                                  
magick convert "resultu.ico" "resultu.ico.png"                                                  
magick convert "resultv.ico" "resultv.ico.png"                                                  
magick convert "resultw.ico" "resultw.ico.png"                                                  
magick convert "resultx.ico" "resultx.ico.png"                                                  
magick convert "result_definition.ico" "result_definition.ico.png"                              
magick convert "Rob.ico" "Rob.ico.png"                                                          
magick convert "Role.ico" "Role.ico.png"                                                        
magick convert "rst.ico" "rst.ico.png"                                                          
magick convert "RTF_file.ico" "RTF_file.ico.png"                                                
magick convert "run.ico" "run.ico.png"                                                          
magick convert "sample hierarchy.ico" "sample hierarchy.ico.png"                                
magick convert "Sample Login.ico" "Sample Login.ico.png"                                        
magick convert "Sample.ico" "Sample.ico.png"                                                    
magick convert "Samplea.ico" "Samplea.ico.png"                                                  
magick convert "Samplec.ico" "Samplec.ico.png"                                                  
magick convert "Samplei.ico" "Samplei.ico.png"                                                  
magick convert "Samplep.ico" "Samplep.ico.png"                                                  
magick convert "Sampler.ico" "Sampler.ico.png"                                                  
magick convert "Samples.ico" "Samples.ico.png"                                                  
magick convert "Sampleu.ico" "Sampleu.ico.png"                                                  
magick convert "Sampleuq.ico" "Sampleuq.ico.png"                                                
magick convert "Samplev.ico" "Samplev.ico.png"                                                  
magick convert "Samplew.ico" "Samplew.ico.png"                                                  
magick convert "Samplex.ico" "Samplex.ico.png"                                                  
magick convert "sample_definition.ico" "sample_definition.ico.png"                              
magick convert "SaveResults.ico" "SaveResults.ico.png"                                          
magick convert "Scheduler.ico" "Scheduler.ico.png"                                              
magick convert "script.ps1" "script.ps1.png"                                                    
magick convert "sdg hierarchy.ico" "sdg hierarchy.ico.png"                                      
magick convert "SDG Login.ico" "SDG Login.ico.png"                                              
magick convert "sdg.ico" "sdg.ico.png"                                                          
magick convert "sdga.ico" "sdga.ico.png"                                                        
magick convert "sdgc.ico" "sdgc.ico.png"                                                        
magick convert "sdgi.ico" "sdgi.ico.png"                                                        
magick convert "sdgp.ico" "sdgp.ico.png"                                                        
magick convert "sdgr.ico" "sdgr.ico.png"                                                        
magick convert "sdgs.ico" "sdgs.ico.png"                                                        
magick convert "sdgu.ico" "sdgu.ico.png"                                                        
magick convert "sdguq.ico" "sdguq.ico.png"                                                      
magick convert "sdgv.ico" "sdgv.ico.png"                                                        
magick convert "sdgw.ico" "sdgw.ico.png"                                                        
magick convert "sdgx.ico" "sdgx.ico.png"                                                        
magick convert "section1.ico" "section1.ico.png"                                                
magick convert "section2.ico" "section2.ico.png"                                                
magick convert "section3.ico" "section3.ico.png"                                                
magick convert "selectall.ico" "selectall.ico.png"                                              
magick convert "SelectMode.ico" "SelectMode.ico.png"                                            
magick convert "Separator.ico" "Separator.ico.png"                                              
magick convert "Server.ico" "Server.ico.png"                                                    
magick convert "ServerExport.ico" "ServerExport.ico.png"                                        
magick convert "ServerImport.ico" "ServerImport.ico.png"                                        
magick convert "Service.ico" "Service.ico.png"                                                  
magick convert "Shift Down.ico" "Shift Down.ico.png"                                            
magick convert "Shift Left.ico" "Shift Left.ico.png"                                            
magick convert "Shift Right.ico" "Shift Right.ico.png"                                          
magick convert "Shift Up.ico" "Shift Up.ico.png"                                                
magick convert "Shortcut.ico" "Shortcut.ico.png"                                                
magick convert "signature entry.ico" "signature entry.ico.png"                                  
magick convert "signature required.ico" "signature required.ico.png"                            
magick convert "signature template.ico" "signature template.ico.png"                            
magick convert "signature.ico" "signature.ico.png"                                              
magick convert "sort_up.ico" "sort_up.ico.png"                                                  
magick convert "sound.ico" "sound.ico.png"                                                      
magick convert "Specification.ico" "Specification.ico.png"                                      
magick convert "spike.ico" "spike.ico.png"                                                      
magick convert "Split Data.ico" "Split Data.ico.png"                                            
magick convert "sprocket_dark.ico" "sprocket_dark.ico.png"                                      
magick convert "standard.ico" "standard.ico.png"                                                
magick convert "Standard_template.ico" "Standard_template.ico.png"                              
magick convert "start run.ico" "start run.ico.png"                                              
magick convert "stock split.ico" "stock split.ico.png"                                          
magick convert "stock.ico" "stock.ico.png"                                                      
magick convert "stockb.ico" "stockb.ico.png"                                                    
magick convert "stockc.ico" "stockc.ico.png"                                                    
magick convert "stockj.ico" "stockj.ico.png"                                                    
magick convert "stockk.ico" "stockk.ico.png"                                                    
magick convert "stockp.ico" "stockp.ico.png"                                                    
magick convert "stockx.ico" "stockx.ico.png"                                                    
magick convert "stock_formulation.ico" "stock_formulation.ico.png"                              
magick convert "stock_template.ico" "stock_template.ico.png"                                    
magick convert "stock_type.ico" "stock_type.ico.png"                                            
magick convert "stop run.ico" "stop run.ico.png"                                                
magick convert "Stop.ico" "Stop.ico.png"                                                        
magick convert "StopAllSpecs.ico" "StopAllSpecs.ico.png"                                        
magick convert "StopThisSpec.ico" "StopThisSpec.ico.png"                                        
magick convert "study login.ico" "study login.ico.png"                                          
magick convert "Study.ico" "Study.ico.png"                                                      
magick convert "Studya.ico" "Studya.ico.png"                                                    
magick convert "Studyc.ico" "Studyc.ico.png"                                                    
magick convert "StudyI.ico" "StudyI.ico.png"                                                    
magick convert "Studyp.ico" "Studyp.ico.png"                                                    
magick convert "Studyr.ico" "Studyr.ico.png"                                                    
magick convert "Studys.ico" "Studys.ico.png"                                                    
magick convert "Studyv.ico" "Studyv.ico.png"                                                    
magick convert "Studyx.ico" "Studyx.ico.png"                                                    
magick convert "Subaliquot.ico" "Subaliquot.ico.png"                                            
magick convert "SubSystem.ico" "SubSystem.ico.png"                                              
magick convert "SubSystemNotFinished.ico" "SubSystemNotFinished.ico.png"                        
magick convert "SubSystemNotPassed.ico" "SubSystemNotPassed.ico.png"                            
magick convert "SubSystemPassed.ico" "SubSystemPassed.ico.png"                                  
magick convert "sub_over.ico" "sub_over.ico.png"                                                
magick convert "Supplier.ico" "Supplier.ico.png"                                                
magick convert "SurfaceHeaders.ico" "SurfaceHeaders.ico.png"                                    
magick convert "suspend stamp.ico" "suspend stamp.ico.png"                                      
magick convert "Synchro.ico" "Synchro.ico.png"                                                  
magick convert "Syntax Aliquot.ico" "Syntax Aliquot.ico.png"                                    
magick convert "Syntax Generic.ico" "Syntax Generic.ico.png"                                    
magick convert "Syntax Plate Plan.ico" "Syntax Plate Plan.ico.png"                              
magick convert "Syntax Plate.ico" "Syntax Plate.ico.png"                                        
magick convert "Syntax Project.ico" "Syntax Project.ico.png"                                    
magick convert "Syntax Rack.ico" "Syntax Rack.ico.png"                                          
magick convert "Syntax Result.ico" "Syntax Result.ico.png"                                      
magick convert "Syntax Sample.ico" "Syntax Sample.ico.png"                                      
magick convert "Syntax SDG.ico" "Syntax SDG.ico.png"                                            
magick convert "syntax signature.ico" "syntax signature.ico.png"                                
magick convert "Syntax Study.ico" "Syntax Study.ico.png"                                        
magick convert "Syntax Worksheet.ico" "Syntax Worksheet.ico.png"                                
magick convert "Syntax.ico" "Syntax.ico.png"                                                    
magick convert "System.ico" "System.ico.png"                                                    
magick convert "Table Wizard.ico" "Table Wizard.ico.png"                                        
magick convert "Table.ico" "Table.ico.png"                                                      
magick convert "Tablespace.ico" "Tablespace.ico.png"                                            
magick convert "tabpage.ico" "tabpage.ico.png"                                                  
magick convert "template_aliquot.ico" "template_aliquot.ico.png"                                
magick convert "template_cherrypicking.ico" "template_cherrypicking.ico.png"                    
magick convert "template_result.ico" "template_result.ico.png"                                  
magick convert "template_sample.ico" "template_sample.ico.png"                                  
magick convert "template_sdg.ico" "template_sdg.ico.png"                                        
magick convert "template_study.ico" "template_study.ico.png"                                    
magick convert "template_test.ico" "template_test.ico.png"                                      
magick convert "template_worksheet.ico" "template_worksheet.ico.png"                            
magick convert "template_worksheet_folder.ico" "template_worksheet_folder.ico.png"              
magick convert "Test.ico" "Test.ico.png"                                                        
magick convert "Testa.ico" "Testa.ico.png"                                                      
magick convert "Testc.ico" "Testc.ico.png"                                                      
magick convert "Testi.ico" "Testi.ico.png"                                                      
magick convert "Testp.ico" "Testp.ico.png"                                                      
magick convert "Testr.ico" "Testr.ico.png"                                                      
magick convert "Tests.ico" "Tests.ico.png"                                                      
magick convert "Testu.ico" "Testu.ico.png"                                                      
magick convert "Testv.ico" "Testv.ico.png"                                                      
magick convert "Testw.ico" "Testw.ico.png"                                                      
magick convert "Testx.ico" "Testx.ico.png"                                                      
magick convert "test_definition.ico" "test_definition.ico.png"                                  
magick convert "Text.ico" "Text.ico.png"                                                        
magick convert "TextNote.ico" "TextNote.ico.png"                                                
magick convert "Text_file.ico" "Text_file.ico.png"                                              
magick convert "Tick.ico" "Tick.ico.png"                                                        
magick convert "Ticked.ico" "Ticked.ico.png"                                                    
magick convert "Ticked2.ico" "Ticked2.ico.png"                                                  
magick convert "tick_overlay.ico" "tick_overlay.ico.png"                                        
magick convert "Tool.ico" "Tool.ico.png"                                                        
magick convert "toolbar.ico" "toolbar.ico.png"                                                  
magick convert "ToolTips.ico" "ToolTips.ico.png"                                                
magick convert "Toxic.ico" "Toxic.ico.png"                                                      
magick convert "Trace.ico" "Trace.ico.png"                                                      
magick convert "Trans.ico" "Trans.ico.png"                                                      
magick convert "Trevor.ico" "Trevor.ico.png"                                                    
magick convert "tristat2.ico" "tristat2.ico.png"                                                
magick convert "tristate.ico" "tristate.ico.png"                                                
magick convert "tristate2.ico" "tristate2.ico.png"                                              
magick convert "UDDE Wizard.ico" "UDDE Wizard.ico.png"                                          
magick convert "unit.ico" "unit.ico.png"                                                        
magick convert "UnitSuite.ico" "UnitSuite.ico.png"                                              
magick convert "UnitSuiteNotFinished.ico" "UnitSuiteNotFinished.ico.png"                        
magick convert "UnitSuiteNotPassed.ico" "UnitSuiteNotPassed.ico.png"                            
magick convert "UnitSuitePassed.ico" "UnitSuitePassed.ico.png"                                  
magick convert "UnitTest.ico" "UnitTest.ico.png"                                                
magick convert "UnitTestEmpty.ico" "UnitTestEmpty.ico.png"                                      
magick convert "UnitTestNotPassed.ico" "UnitTestNotPassed.ico.png"                              
magick convert "UnitTestPassed.ico" "UnitTestPassed.ico.png"                                    
magick convert "UnitTestsPath.ico" "UnitTestsPath.ico.png"                                      
magick convert "Unlock Grid.ico" "Unlock Grid.ico.png"                                          
magick convert "unticke2.ico" "unticke2.ico.png"                                                
magick convert "unticked.ico" "unticked.ico.png"                                                
magick convert "Up.ico" "Up.ico.png"                                                            
magick convert "User Table.ico" "User Table.ico.png"                                            
magick convert "Version Authorised.ico" "Version Authorised.ico.png"                            
magick convert "Version Cancelled.ico" "Version Cancelled.ico.png"                              
magick convert "Version.ico" "Version.ico.png"                                                  
magick convert "Very Toxic.ico" "Very Toxic.ico.png"                                            
magick convert "wait stamp.ico" "wait stamp.ico.png"                                            
magick convert "WALL.ICO" "WALL.ICO.png"                                                        
magick convert "Warn.ico" "Warn.ico.png"                                                        
magick convert "Web-XML.ico" "Web-XML.ico.png"                                                  
magick convert "Web.ico" "Web.ico.png"                                                          
magick convert "window close.ico" "window close.ico.png"                                        
magick convert "window max.ico" "window max.ico.png"                                            
magick convert "window min.ico" "window min.ico.png"                                            
magick convert "window norm.ico" "window norm.ico.png"                                          
magick convert "wizcontrol.ico" "wizcontrol.ico.png"                                            
magick convert "Workflow Login.ico" "Workflow Login.ico.png"                                    
magick convert "Workflow Plate Plan Icon.ico" "Workflow Plate Plan Icon.ico.png"                
magick convert "Workflow.ico" "Workflow.ico.png"                                                
magick convert "workflow_aliquot.ico" "workflow_aliquot.ico.png"                                
magick convert "workflow_aliquot_icon.ico" "workflow_aliquot_icon.ico.png"                      
magick convert "workflow_aliquot_list.ico" "workflow_aliquot_list.ico.png"                      
magick convert "Workflow_Assign_Date.ico" "Workflow_Assign_Date.ico.png"                        
magick convert "Workflow_Assign_Operator.ico" "Workflow_Assign_Operator.ico.png"                
magick convert "Workflow_Assign_Role.ico" "Workflow_Assign_Role.ico.png"                        
magick convert "workflow_broadcast.ico" "workflow_broadcast.ico.png"                            
magick convert "workflow_choice.ico" "workflow_choice.ico.png"                                  
magick convert "workflow_destination.ico" "workflow_destination.ico.png"                        
magick convert "workflow_else.ico" "workflow_else.ico.png"                                      
magick convert "Workflow_Entity.ico" "Workflow_Entity.ico.png"                                  
magick convert "workflow_event.ico" "workflow_event.ico.png"                                    
magick convert "workflow_execution.ico" "workflow_execution.ico.png"                            
magick convert "workflow_false.ico" "workflow_false.ico.png"                                    
magick convert "workflow_field_assignment.ico" "workflow_field_assignment.ico.png"              
magick convert "workflow_field_calculation.ico" "workflow_field_calculation.ico.png"            
magick convert "workflow_field_copy.ico" "workflow_field_copy.ico.png"                          
magick convert "workflow_message.ico" "workflow_message.ico.png"                                
magick convert "workflow_order.ico" "workflow_order.ico.png"                                    
magick convert "workflow_outcome.ico" "workflow_outcome.ico.png"                                
magick convert "workflow_plate.ico" "workflow_plate.ico.png"                                    
magick convert "workflow_plate_filter.ico" "workflow_plate_filter.ico.png"                      
magick convert "workflow_plate_icon.ico" "workflow_plate_icon.ico.png"                          
magick convert "Workflow_Plate_Plan.ico" "Workflow_Plate_Plan.ico.png"                          
magick convert "workflow_post_trigger.ico" "workflow_post_trigger.ico.png"                      
magick convert "workflow_prompted_choice.ico" "workflow_prompted_choice.ico.png"                
magick convert "workflow_prompted_selection.ico" "workflow_prompted_selection.ico.png"          
magick convert "workflow_propagate_authorisation.ico" "workflow_propagate_authorisation.ico.png"
magick convert "workflow_repeat.ico" "workflow_repeat.ico.png"                                  
magick convert "workflow_report.ico" "workflow_report.ico.png"                                  
magick convert "workflow_report_icon.ico" "workflow_report_icon.ico.png"                        
magick convert "workflow_result.ico" "workflow_result.ico.png"                                  
magick convert "workflow_result_icon.ico" "workflow_result_icon.ico.png"                        
magick convert "workflow_result_list.ico" "workflow_result_list.ico.png"                        
magick convert "workflow_sample.ico" "workflow_sample.ico.png"                                  
magick convert "workflow_sample_icon.ico" "workflow_sample_icon.ico.png"                        
magick convert "workflow_sample_list.ico" "workflow_sample_list.ico.png"                        
magick convert "workflow_schedule.ico" "workflow_schedule.ico.png"                              
magick convert "workflow_sdg.ico" "workflow_sdg.ico.png"                                        
magick convert "workflow_sdg_icon.ico" "workflow_sdg_icon.ico.png"                              
magick convert "workflow_selection.ico" "workflow_selection.ico.png"                            
magick convert "workflow_setup.ico" "workflow_setup.ico.png"                                    
magick convert "workflow_specification.ICO" "workflow_specification.ICO.png"                    
magick convert "workflow_split.ico" "workflow_split.ico.png"                                    
magick convert "workflow_step.ico" "workflow_step.ico.png"                                      
magick convert "Workflow_Study_icon.ico" "Workflow_Study_icon.ico.png"                          
magick convert "workflow_test.ico" "workflow_test.ico.png"                                      
magick convert "workflow_test_icon.ico" "workflow_test_icon.ico.png"                            
magick convert "workflow_test_list.ico" "workflow_test_list.ico.png"                            
magick convert "workflow_trigger.ico" "workflow_trigger.ico.png"                                
magick convert "workflow_true.ico" "workflow_true.ico.png"                                      
magick convert "workflow_userchoice.ico" "workflow_userchoice.ico.png"                          
magick convert "workflow_userdefined.ico" "workflow_userdefined.ico.png"                        
magick convert "workflow_validation_Fail.ico" "workflow_validation_Fail.ico.png"                
magick convert "workflow_validation_Pass.ico" "workflow_validation_Pass.ico.png"                
magick convert "worksheet.ico" "worksheet.ico.png"                                              
magick convert "worksheeta.ico" "worksheeta.ico.png"                                            
magick convert "worksheetc.ico" "worksheetc.ico.png"                                            
magick convert "worksheeti.ico" "worksheeti.ico.png"                                            
magick convert "worksheetp.ico" "worksheetp.ico.png"                                            
magick convert "worksheetr.ico" "worksheetr.ico.png"                                            
magick convert "worksheets.ico" "worksheets.ico.png"                                            
magick convert "worksheetu.ico" "worksheetu.ico.png"                                            
magick convert "worksheetv.ico" "worksheetv.ico.png"                                            
magick convert "worksheetw.ico" "worksheetw.ico.png"                                            
magick convert "worksheetx.ico" "worksheetx.ico.png"                                            
magick convert "worksheet_aliquot_type.ico" "worksheet_aliquot_type.ico.png"                    
magick convert "worksheet_format.ico" "worksheet_format.ico.png"                                
magick convert "worksheet_format_field.ico" "worksheet_format_field.ico.png"                    
magick convert "worksheet_new.ico" "worksheet_new.ico.png"                                      
magick convert "worksheet_Sequence.ico" "worksheet_Sequence.ico.png"                            
magick convert "worksheet_session.ico" "worksheet_session.ico.png"                              
magick convert "worksheet_template_sequence.ico" "worksheet_template_sequence.ico.png"          
magick convert "worksheet_template_session.ico" "worksheet_template_session.ico.png"            
magick convert "Workstation.ico" "Workstation.ico.png"                                          
magick convert "World.ico" "World.ico.png"                                                      
magick convert "XML_file.ico" "XML_file.ico.png"                                                
magick convert "zoom.ico" "zoom.ico.png"                                                        
magick convert "zoomin.ico" "zoomin.ico.png"                                                    
magick convert "zoomout.ico" "zoomout.ico.png"                                                  


